services:
    victoire_core.widget_render_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Render }
    #alias to the entity
    victoire.widget.render:
        class: Victoire\Widget\RenderBundle\Entity\WidgetRender
    #alias to the form
    victoire.widget.form.render:
        class: Victoire\Widget\RenderBundle\Form\WidgetRenderType
        tags:
            - { name: form.type , alias: victoire_widget_form_render}

